package generators

import (
	"fmt"
	"os"
	"text/template"

	"github.com/manifoldco/promptui"
)

// apacheTemplate is a basic Apache VirtualHost template used by the generator.
// The user requested only the template; implement the rest as needed.
const apacheTemplate = `# Generated by CONGA
# Domain: {{ .Domain }}
{{- if .UseTLS }}
# TLS enabled (certs at: {{ .CertPath }})
{{- end }}

<VirtualHost *:{{ if .UseTLS }}443{{ else }}80{{ end }}>
    ServerName {{ .Domain }}
    {{- if .UseTLS }}
    SSLEngine on
    SSLCertificateFile {{ .CertPath }}.crt
    SSLCertificateKeyFile {{ .CertPath }}.key
    {{- end }}

    ErrorLog ${APACHE_LOG_DIR}/{{ .Domain }}_error.log
    CustomLog ${APACHE_LOG_DIR}/{{ .Domain }}_access.log combined

    {{- range .Routes }}
    {{- if eq .Type "proxy" }}
    ProxyPass {{ .Path }} http://{{ .Proxy }}
    ProxyPassReverse {{ .Path }} http://{{ .Proxy }}
    {{- else if eq .Type "static" }}
    Alias {{ .Path }} {{ .Directory }}
    <Directory {{ .Directory }}>
        Require all granted
        Options -Indexes
    </Directory>
    {{- end }}
    {{- end }}
</VirtualHost>
`

type Apache struct {
    Domain   string
    UseTLS   bool
    CertPath string
    Routes   []ApacheRoute
}

type ApacheRoute struct {
    Type      string
    Path      string
    Proxy     string
    Directory string
}

func HandleApache(command string) {
    switch command {
    case "generate":
        GenerateApacheConfig()
    case "help":
        PrintApacheHelp()
    default:
        fmt.Printf("Unknown command for apache: %s\n", command)
        PrintApacheHelp()
    }
}

func PrintApacheHelp() {
    fmt.Println("Usage: conga apache [command]")
    fmt.Println("Commands:")
    fmt.Println("  generate   Generate an Apache VirtualHost configuration")
    fmt.Println("  help       Show this help message")
}
// AskApacheDomain moved to shared prompt helpers (AskDomain)

func AskApacheUseTLS() bool {
    prompt := promptui.Prompt{
        Label:     "Use TLS (HTTPS)?",
        IsConfirm: true,
    }

    result, err := runPromptOrExit(prompt)
    if err != nil {
        fmt.Println("Error:", err)
        return false
    }

    return result == "y" || result == "Y"
}
// AskApacheTLS asks if using TLS and optionally where certs live
// AskApacheTLS moved to shared prompt helpers (AskTLS)

// AskNumberOfRoutesApache asks how many routes to configure
// AskNumberOfRoutes for Apache moved to shared prompt helpers (AskNumberOfRoutes)

func AskRouteApache(routeNumber int) ApacheRoute {
    routeTypePrompt := promptui.Select{
        Label: fmt.Sprintf("Route %d type", routeNumber),
        Items: []string{"proxy", "static"},
    } 
    _, routeType, err := runSelectOrExit(routeTypePrompt)
    if err != nil {
        fmt.Println("Error:", err)
        return ApacheRoute{}
    }

    pathPrompt := promptui.Prompt{
        Label:   fmt.Sprintf("Route %d path (e.g., / or /api)", routeNumber),
        Default: "/",
    }
    path, err := runPromptOrExit(pathPrompt)
    if err != nil {
        fmt.Println("Error:", err)
        return ApacheRoute{}
    }
    switch routeType {
    case "proxy":
        proxyPrompt := promptui.Prompt{
            Label:   fmt.Sprintf("Route %d proxy target (e.g., localhost:3000)", routeNumber),
            Default: "localhost:3000",
        }
        proxy, err := runPromptOrExit(proxyPrompt)
        if err != nil {
            fmt.Println("Error:", err)
            return ApacheRoute{}
        }
        return ApacheRoute{Type: "proxy", Path: path, Proxy: proxy}
    
    case "static":
        dirPrompt := promptui.Prompt{
            Label:   fmt.Sprintf("Route %d static directory (e.g., /var/www/html)", routeNumber),
            Default: "/var/www/html",
        }
        directory, err := runPromptOrExit(dirPrompt)
        if err != nil {
            fmt.Println("Error:", err)
            return ApacheRoute{}
        }
        return ApacheRoute{Type: "static", Path: path, Directory: directory}
    }

    // Should never reach here
    return ApacheRoute{}
}


// GenerateApacheConfig manages the entire Apache interactive flow
func GenerateApacheConfig() {
	fmt.Println("\n🔧 Configuring Apache...")

    domain := AskDomain()
    useHttps, certPath := AskTLS(domain, "/etc/ssl/certs/"+domain)

	config := Apache{
		Domain:   domain,
		UseTLS:   useHttps,
		Routes:   []ApacheRoute{},
		CertPath: certPath,
	}

	// Ask for routes
	fmt.Println("\n📍 Configuring routes...")
	numRoutes := AskNumberOfRoutes()

	for i := 1; i <= numRoutes; i++ {
		route := AskRouteApache(i)
		config.Routes = append(config.Routes, route)
	}

	// Display captured configuration
	fmt.Printf("\n✅ Configuration captured:\n")
	fmt.Printf("   Domain: %s\n", config.Domain)
	fmt.Printf("   TLS: %v\n", config.UseTLS)
	fmt.Printf("   CertPath: %s\n", config.CertPath)
	fmt.Printf("   Routes: %d\n\n", len(config.Routes))

	for i, route := range config.Routes {
		fmt.Printf("   Route %d: %s (type: %s)\n", i+1, route.Path, route.Type)
		if route.Type == "proxy" {
			fmt.Printf("      → Proxy to: %s\n", route.Proxy)
		} else {
			fmt.Printf("      → Serve from: %s\n", route.Directory)
		}
	}

	// Generate the file
	filename := askOutput("apache.conf")
	err := WriteApacheConfig(config, filename)
	if err != nil {
		fmt.Printf("\n❌ Error generating config: %v\n", err)
		return
	}

	fmt.Printf("\n✅ Generated: %s\n", filename)
	fmt.Println("\n🎉 Ready to use!")
}

func WriteApacheConfig(config Apache, filename string) error {
    tmpl, err := template.New("apache").Parse(apacheTemplate)
    if err != nil {
        return fmt.Errorf("error parsing template: %v", err)
    }

    file, err := os.Create(filename)
    if err != nil {
        return fmt.Errorf("error creating file: %v", err)
    }
    defer file.Close()

    err = tmpl.Execute(file, config)
    if err != nil {
        return fmt.Errorf("error executing template: %v", err)
    }

    return nil
}