package generators

// apacheTemplate is a basic Apache VirtualHost template used by the generator.
// The user requested only the template; implement the rest as needed.
const apacheTemplate = `# Generated by CONGA
# Domain: {{ .Domain }}
{{- if .UseTLS }}
# TLS enabled (certs at: {{ .CertPath }})
{{- end }}

<VirtualHost *:{{ if .UseTLS }}443{{ else }}80{{ end }}>
    ServerName {{ .Domain }}
    {{- if .UseTLS }}
    SSLEngine on
    SSLCertificateFile {{ .CertPath }}.crt
    SSLCertificateKeyFile {{ .CertPath }}.key
    {{- end }}

    ErrorLog ${APACHE_LOG_DIR}/{{ .Domain }}_error.log
    CustomLog ${APACHE_LOG_DIR}/{{ .Domain }}_access.log combined

    {{- range .Routes }}
    {{- if eq .Type "proxy" }}
    ProxyPass {{ .Path }} http://{{ .Proxy }}
    ProxyPassReverse {{ .Path }} http://{{ .Proxy }}
    {{- else if eq .Type "static" }}
    Alias {{ .Path }} {{ .Directory }}
    <Directory {{ .Directory }}>
        Require all granted
        Options -Indexes
    </Directory>
    {{- end }}
    {{- end }}
</VirtualHost>
`
