package generators

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/manifoldco/promptui"
)

const caddyTemplate = `# Generated by CONGA
# Domain: {{ .Domain }}
{{- if .UseTLS }}
# TLS enabled (certs at: {{ .CertPath }})
{{- end }}

{{ .Domain }} {
	encode gzip
	{{- if .UseTLS }}
	tls {{ .CertPath }}.crt {{ .CertPath }}.key
	{{- else }}
	# TLS disabled (http)
	{{- end }}

	{{- range .Routes }}
	{{- if eq .Type "proxy" }}
	{{ .Path }} {
		reverse_proxy {{ .Proxy }} {
			{{- if .Headers }}
			header_up Host {host}
			header_up X-Real-IP {remote}
			header_up X-Forwarded-For {remote}
			header_up X-Forwarded-Proto {scheme}
			{{- end }}
		}
	}
	{{- else if eq .Type "static" }}
	{{ .Path }} {
		root * {{ .Directory }}
		file_server
	}
	{{- end }}
	{{- end }}
}
`

// CaddyRoute represents a path in Caddy
type CaddyRoute struct {
	Path      string // "/" or "/api/*"
	Type      string // "proxy" or "static"
	Proxy     string // "localhost:3000"
	Directory string // "/var/www/html"
	Headers   bool   // Add standard headers
}

// CaddyConfig is the complete Caddy configuration
type CaddyfileConfig struct {
	Domain   string
	UseTLS   bool
	CertPath string
	Routes   []CaddyRoute
}

// PrintCaddyHelp shows help for Caddy
func PrintCaddyHelp() {
	fmt.Println(`
📘 CONGA Caddy
==============

Command: conga caddy generate

Interactive flow to create a simple Caddyfile with:
- Main domain
- Optional TLS (provide cert/key paths)
- Multiple paths (reverse_proxy or file_server)

Generates a 'Caddyfile' ready to use.`)
}

// HandleCaddy manages caddy commands
func HandleCaddy(command string) {
	switch command {
	case "generate":
		GenerateCaddyConfig()
	case "help":
		PrintCaddyHelp()
	default:
		fmt.Printf("Unknown command: %s\n", command)
	}
}

// AskDomain asks for the main domain
func AskCaddyDomain() string {
	prompt := promptui.Prompt{
		Label:   "Main domain",
		Default: "localhost",
	}

	domain, err := runPromptOrExit(prompt)
	if err != nil {
		fmt.Println("Error:", err)
		return ""
	}

	return domain
}

// AskTLS asks if using TLS and optionally where certs live
func AskTLS(domain string) (bool, string) {
	prompt := promptui.Select{
		Label: "Use TLS (provide cert/key)?",
		Items: []string{"Yes", "No"},
	}

	_, result, err := runSelectOrExit(prompt)
	if err != nil {
		fmt.Println("Error:", err)
		return false, ""
	}

	if result == "Yes" {
		// Ask if user wants to generate local certs with mkcert (reuses nginx generator helpers)
		if AskGenerateCerts() {
			outDir := filepath.Join(".", "certs")
			if err := GenerateCerts(domain, outDir); err != nil {
				fmt.Printf("\n❌ Error generating certs: %v\n", err)
				fmt.Println("Continuing; ensure certs exist at the specified cert path.")
				// fallback to asking for cert path
			} else {
				// Use a conventional in-container path for generated certs
				certPath := "/etc/caddy/certs/" + domain
				fmt.Printf("\n✅ Certificates created at %s (referenced as %s.crt/%s.key)\n", outDir, certPath, certPath)
				return true, certPath
			}
		}

		certPrompt := promptui.Prompt{
			Label:   "Cert path without suffix (e.g. /etc/caddy/certs/example.com)",
			Default: "/etc/caddy/certs/localhost",
		}
		certPath, err := runPromptOrExit(certPrompt)
		if err != nil {
			fmt.Println("Error:", err)
			return true, "/etc/caddy/certs/localhost"
		}
		return true, certPath
	}

	return false, ""
}

// AskNumberOfRoutes asks how many routes to configure
func AskNumberOfRoutesCaddy() int {
	prompt := promptui.Prompt{
		Label:   "Number of routes (paths)",
		Default: "1",
		Validate: func(input string) error {
			num := 0
			_, err := fmt.Sscanf(input, "%d", &num)
			if err != nil {
				return fmt.Errorf("must be a number")
			}
			if num < 1 {
				return fmt.Errorf("must be at least 1")
			}
			return nil
		},
	}

	result, err := runPromptOrExit(prompt)
	if err != nil {
		fmt.Println("Error:", err)
		return 0
	}

	var num int
	fmt.Sscanf(result, "%d", &num)
	return num
}

// AskRouteCaddy asks for details of a single route
func AskRouteCaddy(routeNumber int) CaddyRoute {
	fmt.Printf("\n📌 Route %d:\n", routeNumber)

	pathPrompt := promptui.Prompt{
		Label:   "Path (e.g., / or /api)",
		Default: "/",
	}
	path, err := runPromptOrExit(pathPrompt)
	if err != nil {
		fmt.Println("Error:", err)
		return CaddyRoute{}
	}

	typePrompt := promptui.Select{
		Label: "Type",
		Items: []string{"Proxy", "Static files"},
	}
	_, routeType, err := runSelectOrExit(typePrompt)
	if err != nil {
		fmt.Println("Error:", err)
		return CaddyRoute{}
	}

	route := CaddyRoute{Path: path}

	if routeType == "Proxy" {
		route.Type = "proxy"
		proxyPrompt := promptui.Prompt{
			Label:   "Proxy destination (e.g., localhost:3000)",
			Default: "localhost:3000",
		}
		proxy, err := runPromptOrExit(proxyPrompt)
		if err != nil {
			fmt.Println("Error:", err)
			return CaddyRoute{}
		}
		route.Proxy = proxy

		headersPrompt := promptui.Select{
			Label: "Add standard headers? (Host, X-Real-IP, etc)",
			Items: []string{"Yes", "No"},
		}
		_, headers, err := runSelectOrExit(headersPrompt)
		if err != nil {
			fmt.Println("Error:", err)
			return CaddyRoute{}
		}
		route.Headers = headers == "Yes"

	} else {
		route.Type = "static"
		dirPrompt := promptui.Prompt{
			Label:   "Directory to serve (e.g., /home/user/app/dist)",
			Default: "/var/www/html",
		}
		dir, err := runPromptOrExit(dirPrompt)
		if err != nil {
			fmt.Println("Error:", err)
			return CaddyRoute{}
		}
		route.Directory = dir
	}

	return route
}

// WriteCaddyConfig writes the Caddyfile to a file
func WriteCaddyConfig(config CaddyfileConfig, filename string) error {
	tmpl, err := template.New("caddy").Parse(caddyTemplate)
	if err != nil {
		return fmt.Errorf("error parsing template: %v", err)
	}

	filename, err = NormalizeOutputPath(filename)
	if err != nil {
		return err
	}

	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("error creating file: %v", err)
	}
	defer file.Close()

	err = tmpl.Execute(file, config)
	if err != nil {
		return fmt.Errorf("error executing template: %v", err)
	}

	return nil
}

// GenerateCaddyConfig manages the interactive flow
func GenerateCaddyConfig() {
	fmt.Println("\n🔧 Configuring Caddy...")

	domain := AskCaddyDomain()
	useTLS, certPath := AskTLS(domain)

	config := CaddyfileConfig{
		Domain:   domain,
		UseTLS:   useTLS,
		CertPath: certPath,
		Routes:   []CaddyRoute{},
	}

	fmt.Println("\n📍 Configuring routes...")
	numRoutes := AskNumberOfRoutesCaddy()
	for i := 1; i <= numRoutes; i++ {
		route := AskRouteCaddy(i)
		config.Routes = append(config.Routes, route)
	}

	// Display captured configuration
	fmt.Printf("\n✅ Configuration captured:\n")
	fmt.Printf("   Domain: %s\n", config.Domain)
	fmt.Printf("   TLS: %v\n", config.UseTLS)
	fmt.Printf("   CertPath: %s\n", config.CertPath)
	fmt.Printf("   Routes: %d\n\n", len(config.Routes))

	for i, route := range config.Routes {
		fmt.Printf("   Route %d: %s (type: %s)\n", i+1, route.Path, route.Type)
		if route.Type == "proxy" {
			fmt.Printf("      → Proxy to: %s\n", route.Proxy)
			fmt.Printf("      → Headers: %v\n", route.Headers)
		} else {
			fmt.Printf("      → Serve from: %s\n", route.Directory)
		}
	}

	filename := askOutput("Caddyfile")
	err := WriteCaddyConfig(config, filename)
	if err != nil {
		fmt.Printf("\n❌ Error generating config: %v\n", err)
		return
	}

	fmt.Printf("\n✅ Generated: %s\n", filename)
	fmt.Println("\n🎉 Ready to use!")
}