package generators

import (
	"fmt"
	"os"
	"text/template"

	"github.com/manifoldco/promptui"
)

const nginxTemplate = `# Generated by CONGA
# Domain: {{ .Domain }}
{{- if .UseHTTPS }}
# HTTPS enabled
{{- end }}

{{- if .UseHTTPS }}
server {
    listen 80;
    server_name {{ .Domain }};
    return 301 https://$server_name$request_uri;
}
{{- end }}

server {
    {{- if .UseHTTPS }}
    listen 443 ssl http2;
    {{- else }}
    listen 80;
    {{- end }}
    server_name {{ .Domain }};

    {{- if .UseHTTPS }}
    # SSL Configuration
    ssl_certificate /etc/nginx/certs/{{ .Domain }}.crt;
    ssl_certificate_key /etc/nginx/certs/{{ .Domain }}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    {{- end }}

    # Logs
    access_log /var/log/nginx/{{ .Domain }}_access.log;
    error_log /var/log/nginx/{{ .Domain }}_error.log;

    {{- range .Routes }}
    {{- if eq .Type "proxy" }}

    location {{ .Path }} {
        proxy_pass http://{{ .Proxy }};
        
        {{- if .Headers }}
        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        {{- end }}

        {{- if .WebSocket }}
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        {{- end }}

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    {{- else if eq .Type "static" }}

    location {{ .Path }} {
        alias {{ .Directory }};
        try_files $uri $uri/ =404;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
    {{- end }}
    {{- end }}
}
`

// Route represents a path in Nginx
type Route struct {
	Path      string // "/" or "/api"
	Type      string // "proxy" or "static"
	Proxy     string // "localhost:3000"
	Directory string // "/var/www/html"
	Headers   bool   // Add standard headers
	WebSocket bool   // Support WebSockets (for proxy)
}

// NginxConfig is the complete Nginx configuration
type NginxConfig struct {
	Domain   string
	UseHTTPS bool
	Routes   []Route
}

// PrintNginxHelp shows help for Nginx
func PrintNginxHelp() {
	fmt.Println(`
📘 CONGA Nginx
==============

Command: conga nginx generate

Interactive flow to create Nginx configuration with:
- Main domain
- HTTPS/SSL
- Multiple paths (proxy or static files)
- Standard headers
- Syntax validation

Generates a 'default.conf' file ready to use.`)
}

// HandleNginx manages all nginx commands
func HandleNginx(command string) {
	switch command {
	case "generate":
		GenerateNginxConfig()
	case "help":
		PrintNginxHelp()
	default:
		fmt.Printf("Unknown command: %s\n", command)
	}
}
// AskDomain asks for the main domain
func AskDomain() string {
	prompt := promptui.Prompt{
		Label:   "Main domain",
		Default: "localhost",
	}

	domain, err := prompt.Run()
	if err != nil {
		fmt.Println("Error:", err)
		return ""
	}

	return domain
}
// AskHTTPS asks if using HTTPS
func AskHTTPS() bool {
	prompt := promptui.Select{
		Label: "Use HTTPS?",
		Items: []string{"Yes", "No"},
	}

	_, result, err := prompt.Run()
	if err != nil {
		fmt.Println("Error:", err)
		return false
	}

	return result == "Yes"
}
// AskNumberOfRoutes asks how many routes to configure
func AskNumberOfRoutes() int {
	prompt := promptui.Prompt{
		Label:   "Number of routes (paths)",
		Default: "1",
		Validate: func(input string) error {
			// Simple validation: check if it's a positive number
			num := 0
			_, err := fmt.Sscanf(input, "%d", &num)
			if err != nil {
				return fmt.Errorf("must be a number")
			}
			if num < 1 {
				return fmt.Errorf("must be at least 1")
			}
			return nil
		},
	}

	result, err := prompt.Run()
	if err != nil {
		fmt.Println("Error:", err)
		return 0
	}

	var num int
	fmt.Sscanf(result, "%d", &num)
	return num
}
// AskRoute asks for details of a single route
func AskRoute(routeNumber int) Route {
	fmt.Printf("\n📌 Route %d:\n", routeNumber)

	// Ask for path
	pathPrompt := promptui.Prompt{
		Label:   "Path (e.g., / or /api)",
		Default: "/",
	}
	path, err := pathPrompt.Run()
	if err != nil {
		fmt.Println("Error:", err)
		return Route{}
	}

	// Ask for type
	typePrompt := promptui.Select{
		Label: "Type",
		Items: []string{"Proxy", "Static files"},
	}
	_, routeType, err := typePrompt.Run()
	if err != nil {
		fmt.Println("Error:", err)
		return Route{}
	}

	route := Route{
		Path: path,
	}

	if routeType == "Proxy" {
		route.Type = "proxy"

		// Ask for proxy destination
		proxyPrompt := promptui.Prompt{
			Label:   "Proxy destination (e.g., localhost:3000)",
			Default: "localhost:3000",
		}
		proxy, err := proxyPrompt.Run()
		if err != nil {
			fmt.Println("Error:", err)
			return Route{}
		}
		route.Proxy = proxy

		// Ask for headers
		headersPrompt := promptui.Select{
			Label: "Add standard headers? (Host, X-Real-IP, etc)",
			Items: []string{"Yes", "No"},
		}
		_, headers, err := headersPrompt.Run()
		if err != nil {
			fmt.Println("Error:", err)
			return Route{}
		}
		route.Headers = headers == "Yes"

		// AÑADE ESTO: Ask for WebSocket support
		wsPrompt := promptui.Select{
			Label: "Add WebSocket support? (Upgrade headers)",
			Items: []string{"Yes", "No"},
		}
		_, ws, err := wsPrompt.Run()
		if err != nil {
			fmt.Println("Error:", err)
			return Route{}
		}
		route.WebSocket = ws == "Yes"

	} else {
		route.Type = "static"

		// Ask for directory
		dirPrompt := promptui.Prompt{
			Label:   "Directory to serve (e.g., /home/user/app/dist)",
			Default: "/var/www/html",
		}
		dir, err := dirPrompt.Run()
		if err != nil {
			fmt.Println("Error:", err)
			return Route{}
		}
		route.Directory = dir
	}

	return route
}
func askOutput() string {
	prompt := promptui.Prompt{
		Label:   "Output filename",
		Default: "default.conf",
	}
	
	output, err := prompt.Run()
	if err != nil {
		fmt.Println("Error:", err)
		return "default.conf"
	}
	
	return output
}
// WriteNginxConfig writes the configuration to a file
func WriteNginxConfig(config NginxConfig, filename string) error {
	// Parse the template
	tmpl, err := template.New("nginx").Parse(nginxTemplate)
	if err != nil {
		return fmt.Errorf("error parsing template: %v", err)
	}

	// Normalize path and ensure parent dirs exist
	filename, err = NormalizeOutputPath(filename)
	if err != nil {
		return err
	}

	// Create the file
	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("error creating file: %v", err)
	}
	defer file.Close()

	// Execute template and write to file
	err = tmpl.Execute(file, config)
	if err != nil {
		return fmt.Errorf("error executing template: %v", err)
	}

	return nil
}

// GenerateNginxConfig manages the entire Nginx interactive flow
func GenerateNginxConfig() {
	fmt.Println("\n🔧 Configuring Nginx...")

	domain := AskDomain()
	useHTTPS := AskHTTPS()

	config := NginxConfig{
		Domain:   domain,
		UseHTTPS: useHTTPS,
		Routes:   []Route{},
	}

	// Ask for routes
	fmt.Println("\n📍 Configuring routes...")
	numRoutes := AskNumberOfRoutes()

	for i := 1; i <= numRoutes; i++ {
		route := AskRoute(i)
		config.Routes = append(config.Routes, route)
	}

	// Display captured configuration
	fmt.Printf("\n✅ Configuration captured:\n")
	fmt.Printf("   Domain: %s\n", config.Domain)
	fmt.Printf("   HTTPS: %v\n", config.UseHTTPS)
	fmt.Printf("   Routes: %d\n\n", len(config.Routes))

	for i, route := range config.Routes {
		fmt.Printf("   Route %d: %s (type: %s)\n", i+1, route.Path, route.Type)
		if route.Type == "proxy" {
			fmt.Printf("      → Proxy to: %s\n", route.Proxy)
			fmt.Printf("      → Headers: %v\n", route.Headers)
			fmt.Printf("      → WebSocket: %v\n", route.WebSocket)
		} else {
			fmt.Printf("      → Serve from: %s\n", route.Directory)
		}
	}

	// Generate the file
	filename := askOutput()
	err := WriteNginxConfig(config, filename)
	if err != nil {
		fmt.Printf("\n❌ Error generating config: %v\n", err)
		return
	}

	fmt.Printf("\n✅ Generated: %s\n", filename)
	fmt.Println("\n🎉 Ready to use!")
}