package generators

import (
	"fmt"
	"os"
	"text/template"

	"github.com/manifoldco/promptui"
)

const WireguardTemplate = `# Generated by CONGA
[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .Address }}
DNS = {{ .DNS }}
ListenPort = {{ .ListenPort }}

{{- range .Peers }}

[Peer]
PublicKey = {{ .PublicKey }}
AllowedIPs = {{ .AllowedIPs }}
{{- if .Endpoint }}
Endpoint = {{ .Endpoint }}
{{- end }}
{{- if .PersistentKeepalive }}
PersistentKeepalive = {{ .PersistentKeepalive }}
{{- end }}
{{- end }}
`

type WireGuardConfig struct {
	InterfaceName string // "wg0"
	PrivateKey    string 
	Address       string // 10.0.0.1/24
	DNS           string // 8.8.8.8
	ListenPort    string // 51820
	Peers         []WireGuardPeer
}

type WireGuardPeer struct {
	PublicKey  string // ask for public key of the peer
	AllowedIPs string // 10.0.0.2/32
	Endpoint   string // 192.168.1.1:51820 if is client, empty if is server
	PersistentKeepalive string // 25
}

// PrintWireGuardHelp shows help for WireGuard
func PrintWireGuardHelp() {
	fmt.Println(`
CONGA WireGuard
===============

Usage: conga wireguard generate <server|client>

Interactive flow to create a WireGuard configuration with:
- Interface name
- Private key
- Address
- DNS
- Listen port
- Peers

Generates a '<interface>.conf' file ready to use.`)
}

// HandleWireGuard manages all WireGuard commands
func HandleWireGuard(args []string) {
	if len(args) == 0 {
		PrintWireGuardHelp()
		return
	}

	switch args[0] {
	case "generate":
		if len(args) < 2 {
			fmt.Println("Error: you must specify either 'server' or 'client'.")
			PrintWireGuardHelp()
			return
		}
		mode := args[1]
		if mode != "server" && mode != "client" {
			fmt.Printf("Unknown mode: %s\n", mode)
			PrintWireGuardHelp()
			return
		}
		GenerateWireGuardConfig(mode)
	case "help":
		PrintWireGuardHelp()
	default:
		fmt.Printf("Unknown command: %s\n", args[0])
	}
}
func askWireGuardInterfaceName(defaultVal string) string {
	if defaultVal == "" {
		defaultVal = "wg0"
	}
	result, err := runPromptOrExit(promptui.Prompt{
		Label:   "Interface name",
		Default: defaultVal,
	})
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}

func askWireGuardPrivateKey() string {
	result, err := runPromptOrExit(promptui.Prompt{
		Label: "Private key",
	})
	if err != nil {
		fmt.Println("Error:", err)
		return ""
	}
	return result
}
func askWireGuardAddress(defaultVal string) string {
	if defaultVal == "" {
		defaultVal = "10.0.0.1/24"
	}
	result, err := runPromptOrExit(promptui.Prompt{
		Label:   "Address (CIDR format)",
		Default: defaultVal,
	})
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}
func askWireGuardDNS(defaultVal string) string {
	if defaultVal == "" {
		defaultVal = "8.8.8.8"
	}
	result, err := runPromptOrExit(promptui.Prompt{
		Label:   "DNS",
		Default: defaultVal,
	})
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}
func askWireGuardListenPort(defaultVal string) string {
	result, err := runPromptOrExit(promptui.Prompt{
		Label:   "Listen port",
		Default: defaultVal,
	})
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}
func askWireGuardPeerCount(defaultVal string) int {
	if defaultVal == "" {
		defaultVal = "1"
	}
	result, err := runPromptOrExit(promptui.Prompt{
		Label:   "Number of peers",
		Default: defaultVal,
	})
	if err != nil {
		fmt.Println("Error:", err)
		return 1
	}
	var count int
	fmt.Sscanf(result, "%d", &count)
	if count < 0 {
		count = 0
	}
	return count
}
func askWireGuardPeerPublicKey(peerNum int) string {
	result, err := runPromptOrExit(promptui.Prompt{
		Label: fmt.Sprintf("Peer %d public key", peerNum),
	})
	if err != nil {
		fmt.Println("Error:", err)
		return ""
	}
	return result
}
func askWireGuardPeerAllowedIPs(peerNum int, defaultVal string) string {
	p := promptui.Prompt{Label: fmt.Sprintf("Peer %d allowed IPs", peerNum)}
	if defaultVal != "" {
		p.Default = defaultVal
	}
	result, err := runPromptOrExit(p)
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}
func askWireGuardPeerEndpoint(peerNum int, defaultVal string) string {
	p := promptui.Prompt{Label: fmt.Sprintf("Peer %d endpoint", peerNum)}
	if defaultVal != "" {
		p.Default = defaultVal
	}
	result, err := runPromptOrExit(p)
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}
func askWireGuardPeerPersistentKeepalive(peerNum int, defaultVal string) string {
	p := promptui.Prompt{Label: fmt.Sprintf("Peer %d persistent keepalive", peerNum)}
	if defaultVal != "" {
		p.Default = defaultVal
	}
	result, err := runPromptOrExit(p)
	if err != nil {
		fmt.Println("Error:", err)
		return defaultVal
	}
	return result
}

func WriteWireGuardConfig(config WireGuardConfig) error {
	tmpl, err := template.New("wireguard").Parse(WireguardTemplate)
	if err != nil {
		return err
	}

	filename := fmt.Sprintf("%s.conf", config.InterfaceName)
	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("error creating file: %v", err)
	}
	defer file.Close()

	err = tmpl.Execute(file, config)
	if err != nil {
		return fmt.Errorf("error executing template: %v", err)
	}

	return nil

}

func GenerateWireGuardConfig(mode string) {
	// Delegate to specific generators for clarity
	if mode == "server" {
		generateWireGuardServer()
		return
	}
	if mode == "client" {
		generateWireGuardClient()
		return
	}
}

func promptBaseSettings(ifaceDefault, addrDefault, dnsDefault, listenDefault, peerCountDefault string, askListen bool) (string, string, string, string, string, int) {
	interfaceName := askWireGuardInterfaceName(ifaceDefault)
	privateKey := askWireGuardPrivateKey()
	address := askWireGuardAddress(addrDefault)
	dns := askWireGuardDNS(dnsDefault)
	listenPort := ""
	if askListen {
		listenPort = askWireGuardListenPort(listenDefault)
	}
	peerCount := askWireGuardPeerCount(peerCountDefault)

	return interfaceName, privateKey, address, dns, listenPort, peerCount

}

func collectPeers(mode string, peerCount int) []WireGuardPeer {
	peers := make([]WireGuardPeer, peerCount)
	for i := 0; i < peerCount; i++ {
		fmt.Printf("\n🔗 Configuring Peer %d...\n", i+1)
		publicKey := askWireGuardPeerPublicKey(i + 1)

		allowedDefault := "10.0.0.2/32"
		if mode == "client" {
			allowedDefault = "0.0.0.0/0"
		}
		allowedIPs := askWireGuardPeerAllowedIPs(i+1, allowedDefault)

		var endpoint string
		if mode == "client" {
			endpointDefault := "server:51820"
			endpoint = askWireGuardPeerEndpoint(i+1, endpointDefault)
		} else {
			// Server mode: do not ask for endpoint (server doesn't need peer endpoint)
			endpoint = ""
		}

		keepaliveDefault := ""
		if mode == "client" {
			keepaliveDefault = "25"
		}
		keepalive := askWireGuardPeerPersistentKeepalive(i+1, keepaliveDefault)

		peers[i] = WireGuardPeer{
			PublicKey:  publicKey,
			AllowedIPs: allowedIPs,
			Endpoint:   endpoint,
			PersistentKeepalive: keepalive,
		}
	}
	return peers
}

func generateWireGuardServer() {
	fmt.Println("\n🔧 Configuring WireGuard (server)...")
	fmt.Println("Recommended: use 10.0.0.1/24 for the server interface and port 51820. Generate the key with 'wg genkey'.")

	ifaceDef := "wg0"
	addrDef := "10.0.0.1/24"
	dnsDef := "8.8.8.8"
	listenDef := "51820"
	peerCountDef := "1"

	interfaceName, privateKey, address, dns, listenPort, peerCount := promptBaseSettings(ifaceDef, addrDef, dnsDef, listenDef, peerCountDef, true)

	peers := collectPeers("server", peerCount)

	config := WireGuardConfig{
		InterfaceName: interfaceName,
		PrivateKey:    privateKey,
		Address:       address,
		DNS:           dns,
		ListenPort:    listenPort,
		Peers:         peers,
	}

	if err := WriteWireGuardConfig(config); err != nil {
		fmt.Println("Error writing config:", err)
	} else {
		fmt.Println("✅ WireGuard server configuration generated successfully!")
	}
}

func generateWireGuardClient() {
	fmt.Println("\n🔧 Configuring WireGuard (client)...")
	fmt.Println("Recommended: use a /32 address for the client (e.g. 10.0.0.2/32). Generate the key with 'wg genkey' and get the server public key with 'wg pubkey'.")

	ifaceDef := "wg0"
	addrDef := "10.0.0.2/32"
	dnsDef := "8.8.8.8"
	listenDef := ""
	peerCountDef := "1"

	interfaceName, privateKey, address, dns, listenPort, peerCount := promptBaseSettings(ifaceDef, addrDef, dnsDef, listenDef, peerCountDef, false)

	peers := collectPeers("client", peerCount)

	config := WireGuardConfig{
		InterfaceName: interfaceName,
		PrivateKey:    privateKey,
		Address:       address,
		DNS:           dns,
		ListenPort:    listenPort,
		Peers:         peers,
	}

	if err := WriteWireGuardConfig(config); err != nil {
		fmt.Println("Error writing config:", err)
	} else {
		fmt.Println("✅ WireGuard client configuration generated successfully!")
	}
}